Rochester:
  enabled: true
  phone: 01634 803100
  email: pvb.rochester@maildrop.dsd.io
  address:
    - 1 Fort Road
    - Rochester
    - Kent
    - ME1 3QS
  unbookable:
    - 2013-12-25
    - 2013-12-26
    - 2014-12-25
    - 2014-12-26
  slots:
    mon:
      - 1400-1600
    tue:
      - 1400-1600
    wed:
      - 1400-1600
    thu:
      - 1400-1600
    sat:
      - 0915-1115
      - 1400-1600
    sun:
      - 1400-1600
Durham:
  enabled: true
  phone: 0191 3323417
  email: pvb.durham@maildrop.dsd.io
  address:
    - Old Elvet
    - Durham
    - DH1 3HU
  unbookable:
    - 2014-04-18
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    mon:
      - 1345-1545
    tue:
      - 1345-1545
      - 1715-1900
    wed:
      - 1345-1545
      - 1715-1900
    thu:
      - 1345-1545
    fri:
      - 1345-1545
    sat:
      - 0900-1145
      - 1345-1645
    sun:
      - 0900-1145
      - 1345-1645
Cardiff:
  enabled: true
  phone: 029 20923327
  email: pvb.cardiff@maildrop.dsd.io
  address:
    - Knox Road
    - Cardiff
    - CF24 0UG
  unbookable:
    - 2014-02-05
    - 2014-03-05
    - 2014-04-02
    - 2014-04-18
    - 2014-05-07
    - 2014-06-04
    - 2014-07-02
    - 2014-08-06
    - 2014-09-03
    - 2014-10-01
    - 2014-11-05
    - 2014-12-03
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    mon:
      - 1350-1450
      - 1450-1550
    tue:
      - 1350-1450
      - 1450-1550
    wed:
      - 1350-1450
      - 1450-1550
    thu:
      - 1350-1450
      - 1450-1550
    fri:
      - 1350-1450
      - 1450-1550
    sat:
      - 0945-1115
      - 1350-1520
    sun:
      - 1350-1520
  slot_anomalies:
    2014-04-21:
      - 0945-1115
      - 1350-1520
    2014-05-05:
      - 0945-1115
      - 1350-1520
    2014-05-26:
      - 0945-1115
      - 1350-1520
Gartree:
  enabled: true
  phone: 01858 426 727
  email: pvb.gartree@maildrop.dsd.io
  address:
    - Gallow Field Rd
    - Market Harborough
    - Leicestershire
    - LE16 7RP
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    tue:
      - 1400-1600
    thu:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
Brinsford: 
  enabled: true
  phone: 01902 533 450
  email: pvb.brinsford@maildrop.dsd.io
  address:
    - New Road  
    - Featherstone
    - Wolverhampton
    - WV10 7PY
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-05-05
    - 2014-05-26
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    mon:
      - 1330-1600
    tue:
      - 1330-1600
    thu:
      - 1330-1600
    sat:
      - 1330-1600
    sun:
      - 1330-1600
Drake Hall: 
  enabled: true
  phone: 0300 060 6501
  email: pvb.drakehall@maildrop.dsd.io
  address:
    - Eccleshall  
    - Staffordshire
    - ST21 6LQ
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-05-05
    - 2014-05-26
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    tue:
      - 1330-1545
    sat:
      - 1330-1545
    sun:
      - 1330-1545
Werrington: 
  enabled: true
  phone: 01782 463 300
  email: pvb.werrington@maildrop.dsd.io
  address:
    - Werrington  
    - Stoke-On-Trent
    - ST9 0DX
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-05-05
    - 2014-05-26
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    wed:
      - 1400-1600
    fri: 
      - 1400-1600
    sat:
      - 1430-1630
    sun:
      - 1430-1630
Featherstone: 
  enabled: true
  phone: 001902 703000
  email: pvb.featherstone@maildrop.dsd.io
  address:
    - New Road  
    - Featherstone
    - Wolverhampton
    - WV10 7PU
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-05-05
    - 2014-05-26
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    tue:
      - 1400-1600
    wed: 
      - 1400-1600
    thu: 
      - 1400-1600
    fri:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
Stoke Heath: 
  enabled: true
  phone: 0300 0606506
  email: pvb.stokeheath@maildrop.dsd.io
  address:
    - Market Drayton  
    - Shropshire
    - TF9 2JL
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-05-05
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    mon:
      - 1400-1600
    tue:
      - 1400-1600
    wed:
      - 1400-1600
    thu:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
Swinfen Hall: 
  enabled: true
  phone: 01543 484 000
  email: pvb.swinfenhall@maildrop.dsd.io
  address:
    - Swinfen Hall  
    - FLichfield
    - Staffordshire
    - WS14 9QS
  unbookable:
    - 2014-04-18
    - 2014-04-21
    - 2014-05-05
    - 2014-05-26
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    tue:
      - 1400-1600
    wed:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
Hewell: 
  enabled: true
  phone: 01527 785000
  email: pvb.hewell@maildrop.dsd.io
  address:
    - Hewell Lane  
    - Redditch
    - Worcestershire
    - B97 6QS
  unbookable:
    - 2014-05-05
    - 2014-05-26
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
  slots:
    mon:
      - 1400-1630
    tue:
      - 1400-1630
    wed: 
      - 1400-1630
    thu:
      - 1400-1630
    fri: 
      - 1430-1630
    sat:
      - 0930-1130
      - 1430-1630
    sun:
      - 0930-1130
      - 1430-1630
Foston Hall: 
  enabled: true
  phone: 01283 584357 
  email: pvb.fostonhall@maildrop.dsd.io
  address:
    - Foston Hall
    - Derby
    - Foston
    - DE65 5DN
  unbookable:
    - 2015-04-03 
    - 2014-12-25
  slots:
    mon:
      - 1400-1600
    wed: 
      - 1400-1600
    fri: 
      - 1400-1600
    sat:
      - 0930-1130
      - 1400-1600
    sun:
      - 0930-1130
      - 1400-1600
Holloway:
  enabled: false
  phone: 020 7979 4751 
  email: pvb.holloway@maildrop.dsd.io
  address:
    - Pankhurst Road
    - London
    - N7 0NU
  unbookable:
    - 2014-06-14
    - 2014-07-12
    - 2014-08-09
    - 2014-09-13
    - 2014-10-11
    - 2014-11-08
    - 2014-12-06
  slots:
    mon:
      - 1430-1530
    tue: 
      - 0930-1030
      - 1430-1530
    wed: 
      - 0930-1030
      - 1430-1530
    thu:
      - 0930-1030
      - 1430-1530
      - 1800-1900
    fri: 
      - 0930-1030
    sat:
      - 1400-1500
      - 1530-1630
    sun:
      - 1400-1500
      - 1530-1630
  slot_anomalies:
    2014-05-21:
      - 0930-1030
    2014-06-18:
      - 0930-1030
    2014-07-29:
      - 0930-1030
    2014-08-20:
      - 0930-1030
    2014-09-24:
      - 0930-1030
    2014-10-22:
      - 0930-1030
    2014-11-19:
      - 0930-1030
    2014-12-18:
      - 0930-1030
    2014-05-29:
      - 0930-1030
    2014-07-24:
      - 0930-1030
    2014-08-21:
      - 0930-1030
    2014-10-30:
      - 0930-1030
    2014-12-18:
      - 0930-1030
Bristol: 
  enabled: false
  phone: 01173 732358 
  email: SocialVisits.Bristol@hmps.gsi.gov.uk
  address:
    - 19 Cambridge Road
    - Bristol
    - BS7 8PS
  unbookable:
    - 2014-12-25
    - 2014-12-26
    - 2015-04-03
  slots:
    mon:
      - 1400-1600
    tue:
      - 1400-1600
    wed: 
      - 1400-1600
    thu:
      - 1400-1600
    fri: 
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
Buckley Hall: 
  enabled: false
  phone: 01706 514350 
  email: SocialVisits.buckleyhall@hmps.gsi.gov.uk
  address:
    - Buckley Road
    - OL12 9DP
  unbookable:
    - 2014-12-25
    - 2014-12-26
    - 2015-01-01
    - 2015-04-03
  slots:
    mon:
      - 1400-1600
    tue:
      - 1400-1600
    wed: 
      - 1400-1600
      - 1745-1845
    thu:
      - 1400-1600
    fri: 
      - 1400-1600
    sat:
      - 0930-1130
      - 1400-1600 
    sun:
      - 0930-1130
      - 1400-1600
Bure: 
  enabled: false
  phone: 01603 326252
  email: SocialVisits.bure@hmps.gsi.gov.uk
  address:
    - Jaguar Drive
    - NR10 5GB
  unbookable:
    - 2014-12-25
    - 2015-01-01
    - 2015-04-03
  slots:
    fri: 
      - 1400-1600
    sat:
      - 0930-1130
      - 1400-1600 
    sun:
      - 0930-1130
      - 1400-1600
Coldingley: 
  enabled: false
  phone: 01483 344418
  email: SocialVisits.coldingley@hmps.gsi.gov.uk
  address:
    - Shaftesbury Road
    - GU24 9EX
  unbookable:
    - 2014-12-25
    - 2014-07-30
    - 2014-08-20
    - 2014-10-29
    - 2014-12-19
    - 2015-01-01
    - 2015-04-03
  slots:
    mon: 
      - 1400-1545
    wed:
      - 1400-1545 
    thu:
      - 1400-1545
    fri:
      - 1800-1900
    sat:
      - 1400-1545
    sun:
      - 1400-1545
Cookham Wood: 
  enabled: false
  phone: 01634 202557
  email: SocialVisits.CookhamWood@hmps.gsi.gov.uk
  address:
    - Sir Evelyn Road
    - ME1 3LU
  unbookable:
    - 2014-12-25
  slots:
    wed:
      - 1815-1930 
    sat:
      - 0930-1130
      - 1430-1630
    sun:
      - 0930-1130
      - 1430-1630
Deerbolt:  
  enabled: false
  phone: 01833 633349
  email: SocialVisits.Deerbolt@hmps.gsi.gov.uk
  address:
    - Bowes Road
    - DL12 9BG 
  unbookable:
    - 2014-12-25
    - 2014-12-26
    - 2015-04-03
  slots:
    thu:
      - 1345-1545
    sat:
      - 1345-1545
    sun:
      - 1345-1545
Exeter:  
  enabled: false
  phone: 01392 41 5833
  email: SocialVisits.Exeter@hmps.gsi.gov.uk
  address:
    - New North Road
    - EX4 4EX 
  unbookable:
    - 2014-12-25
    - 2014-12-26
    - 2015-04-03
  slots:
    mon:
      - 1415-1615
    tue:
      - 1415-1615
    thu:
      - 1415-1615
    fri: 
      - 1415-1615
    sat:
      - 1415-1615
    sun:
      - 1415-1615
Lewes:  
  enabled: false
  phone: 01273785277
  email: SocialVisits.Lewes@hmps.gsi.gov.uk
  address:
    - 1 Brighton Road
    - BN7 1EA 
  unbookable:
    - 2014-12-25
    - 2015-01-01
    - 2015-04-03
  slots:
    mon:
      - 0930-1100
      - 1410-1535
    tue:
      - 1410-1535
    wed:
      - 0930-1100
      - 1410-1535
    thu:
      - 1410-1535
    fri: 
      - 0930-1100
      - 1410-1535
    sat:
      - 1410-1535
    sun:
      - 1410-1535
Moorland Closed:  
  enabled: false
  phone: 01302523087
  email: SocialVisits.MoorlandClosed@hmps.gsi.gov.uk
  address:
    - Bawtry Road
    - DN7 6BW 
  unbookable:
    - 2014-12-25
  slots:
    wed:
      - 1340-1545
    thu:
      - 1340-1545
    sat:
      - 1340-1545
    sun:
      - 1340-1545
Onley:  
  enabled: false
  phone: 01788 523 402
  email: SocialVisits.Onley@hmps.gsi.gov.uk
  address:
    - Willoughby
    - CV23 8AP 
  unbookable:
    - 2014-12-25
  slots:
    mon:
      - 1345-1445
      - 1515-1615
    tue:
      - 1345-1445
      - 1515-1615
    wed:
      - 1345-1445
      - 1515-1615
    thu:
      - 1345-1445
      - 1515-1615
    fri:
      - 1430-1600
    sat:
      - 1345-1445
      - 1515-1615
    sun:
      - 1345-1445
      - 1515-1615
The Mount:  
  enabled: false
  phone: 01442 836352
  email: SocialVisits.TheMount@hmps.gsi.gov.uk
  address:
    - Molyneaux Avenue
    - HP3 0NZ 
  unbookable:
    - 2014-12-25
  slots:
    thu:
      - 1400-1600
      - 1500-1600
    fri:
      - 1400-1600
      - 1500-1600
    sat:
      - 0900-1100
      - 1000-1100
      - 1400-1600
      - 1500-1600
    sun:
      - 0900-1100
      - 1000-1100
      - 1400-1600
      - 1500-1600
Wayland:  
  enabled: false
  phone: 001953 804152
  email: SocialVisits.Wayland@hmps.gsi.gov.uk
  address:
    - Griston
    - IP25 6RL 
  unbookable:
    - 2014-12-25
  slots:
    tue:
      - 1400-1600
    wed:
      - 1400-1600
    thu:
      - 1400-1600
    fri:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
Wealstun:  
  enabled: false
  phone: 01937 444599
  email: SocialVisits.Wealstun@hmps.gsi.gov.uk
  address:
    - Church Causeway
    - LS23 7AZ 
  unbookable:
    - 2014-12-25
  slots:
    mon:
      - 0930-1130
      - 1330-1530
    tue:
      - 0930-1130
      - 1330-1530
    wed:
      - 0930-1130
      - 1330-1530
    thu:
      - 0930-1130
      - 1330-1530
    sat:
      - 0930-1130
      - 1345-1600
    sun:
      - 0930-1130
      - 1345-1600
Bedford:
  enabled: false
  phone: '01234 373196'
  email: SocialVisits.Bedford@hmps.gsi.gov.uk
  address:
    - 'St. Loyes Street'
    - 'MK40 1HG'
  unbookable:
    - 2014-12-25
  slots:
    mon:
      - 1345-1445
      - 1515-1615
    sat:
      - 1345-1445
      - 1515-1615
    sun:
      - 1345-1445
      - 1515-1615
    thu:
      - 1345-1445
      - 1515-1615
    tue:
      - 1345-1445
      - 1515-1615
    wed:
      - 1345-1445
      - 1515-1615
Preston:
  enabled: false
  phone: '01772 444666'
  email: ""
  address:
    - '2 Ribbleton Lane'
    - 'PR1 5AB '
  unbookable:
    - 2014-12-25
  slots:
    fri:
      - 1400-1600
    mon:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
    thu:
      - 1400-1600
    tue:
      - 1400-1600
    wed:
      - 1400-1600
Maidstone:
  enabled: false
  phone: '016220775619'
  email: Socialvisits.maidstone@hmps.gsi.gov.uk
  address:
    - '36 County Road'
    - 'ME14 1UZ '
  unbookable:
    - 2014-12-25
  slots:
    fri:
      - 1400-1625
    mon:
      - 1400-1625
    sat:
      - 1400-1625
    sun:
      - 1400-1625
    thu:
      - 1400-1625
    wed:
      - 1400-1625
'Warren Hill':
  enabled: false
  phone: '020 8588 4002'
  email: SocialVisits.WarrenHill@hmps.gsi.gov.uk
  address:
    - Hollesley
    - 'IP12 3JW '
  unbookable:
    - 2014-12-25
  slots:
    sat:
      - 1400-1600
    sun:
      - 1400-1600
    wed:
      - 1415-1600
Wetherby:
  enabled: false
  phone: '01937 544207'
  email: SocialVisits.Wetherby@hmps.gsi.gov.uk
  address:
    - 'York Road'
    - 'LS22 5ED '
  unbookable:
    - 2014-12-25
  slots:
    fri:
      - 1400-1600
    mon:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
    thu:
      - 1400-1600
    tue:
      - 1400-1600
    wed:
      - 1400-1600
Erlestoke:
  enabled: false
  phone: '01380 814264'
  email: eecmbookavisit@hmps.gsi.gov.uk
  address:
    - DEVIZES
    - 'SN10 5TU'
  unbookable:
    - 2014-12-25
  slots:
    sat:
      - 1400-1600
    sun:
      - 1400-1600
    thu:
      - 1345-1600
    tue:
      - 1345-1600
Chelmsford:
  enabled: false
  phone: '01245 552265'
  email: SocialVisits.Chelmsford@hmps.gsi.gov.uk
  address:
    - '200 Springfield Road'
    - 'CM2 6LQ '
  unbookable:
    - 2014-12-25
  slots:
    mon:
      - 1415-1600
    sat:
      - 0930-1100
      - 1430-1545
    sun:
      - 0930-1100
      - 1430-1545
    thu:
      - 1415-1600
    tue:
      - 1415-1600
    wed:
      - 1415-1600
Stocken:
  enabled: false
  phone: '01780 795156'
  email: SocialVisits.Stocken@hmps.gsi.gov.uk
  address:
    - 'Stocken Hall Road'
    - 'LE15 7RD'
  unbookable:
    - 2014-12-25
  slots:
    fri:
      - 1345-1545
    sat:
      - 0915-1115
      - 1345-1545
    sun:
      - 0915-1115
      - 1345-1545
    wed:
      - 1345-1545
Dartmoor:
  enabled: false
  phone: '01822 322022'
  email: ""
  address:
    - Princetown
    - 'PL20 6RR'
  unbookable:
    - 2014-12-25
  slots:
    fri:
      - 1400-1600
    sat:
      - 1400-1600
    sun:
      - 1400-1600
    thu:
      - 1400-1600
    wed:
      - 1400-1600
'Low Newton':
  enabled: false
  phone: '0191 376 4147'
  email: SocialVisits.LowNewton@hmps.gsi.gov.uk
  address:
    - Brasside
    - 'DH1 5YA'
  unbookable:
    - 2014-12-25
  slots:
    fri:
      - 1415-1545
    sat:
      - 1400-1545
    sun:
      - 1400-1545
    thu:
      - 1415-1545
    tue:
      - 1415-1545
Aylesbury:
  enabled: false
  phone: '01296 444099'
  email: visitsbookingaylesbury@hmps.gsi.gov.uk
  address:
    - 'Bierton Road'
    - 'HP20 1EH'
  unbookable:
    - 2014-12-25
  slots:
    mon:
      - 1415-1615
    sat:
      - 1400-1535
    sun:
      - 1400-1535
    thu:
      - 1415-1615
    wed:
      - 1415-1615
